# yaml-language-server: $schema=https://raw.githubusercontent.com/xt0rted/secrets-sync/main/settings.schema.json
defaults:
  actions: false
  dependabot: true

secrets:
  - name: SECRET_SYNC
    value: env/SECRET_SYNC
    actions: false
    dependabot: true
    repos:
      -  RaptorDVZ/testing
      -  RaptorDVZ/myfile

  - name: C
    value: env/C
    actions: false
    dependabot: true
    repos:
      -  RaptorDVZ/testing
      -  RaptorDVZ/myfile
