name: "Secrets Sync - Artifactory NPM"



on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/secret-sync-artifactory-npm.yaml' # Repository/Environment Secrets
      - '.github/secret-sync-artifactory-npm.yaml' # Dependabot Secrets

jobs:
  syncSecrets:
    name: "Sync Github Secrets to Repos"
    runs-on: ubuntu-latest
    steps:
      # WMS Jfrog (Cloud) Artifactory Credentials (Old Secret Name)
      - name: Secrets Sync - Artifactory - NPM
        uses: google/secrets-sync-action@v1.7.1
        with:
          SECRETS: |
            ^SECRET_SYNC
            ^C
          REPOSITORIES: |
            RaptorDVZ/testing
            RaptorDVZ/myfile
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          CONCURRENCY: 2
          repositories_list_regex: false
        env:
          SECRET_SYNC: ${{ secrets.SECRET_SYNC }}

      # For as long as Google doesn't support Dependabot Secrets
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: xt0rted Secrets Sync - Artifactory NPM
        uses: xt0rted/secrets-sync@v1
        with:
          repo_token: ${{ secrets.TOKEN }}
          config: .github/secret-sync-artifactory-npm.yaml
        env:
          SECRET_SYNC: ${{ secrets.SECRET_SYNC }}
          C: ${{ secrets.C }}
