name: "Secrets Sync - Artifactory NPM"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/secret-sync-artifactory-npm.yaml' # Repository/Environment Secrets
      - '.github/secret-sync-artifactory-npm.yaml' # Dependabot Secrets

jobs:
  syncSecrets:
    name: "Sync Github Secrets to Repos"
    runs-on: ubuntu-latest
    steps:
      # WMS Jfrog (Cloud) Artifactory Credentials (Old Secret Name)
      - name: Secrets Sync - Artifactory - NPM
        uses: google/secrets-sync-action@v1.7.1
        with:
          SECRETS: |
            ^ARTIFACTORY_NPM_AUTH
            ^ARTIFACTORY_NPM_URL
          REPOSITORIES: |
            BY-Product-Development/exec-wms-label-designer
            BY-Product-Development/exec-wms-delivery-deployments-client
            BY-Product-Development/exec-wms-delivery-github-actions
            BY-Product-Development/exec-wms-delivery-test-repo
            BY-Product-Development/exec-wms-delivery-internal-test3
            BY-Product-Development/exec-wms-delivery-internal-test2
            BY-Product-Development/exec-wms-delivery-internal-test1
            BY-Product-Development/exec-wms-report-designer
            BY-Product-Development/exec-wms-yard-management-deployments
            BY-Product-Development/exec-wms-yard-management-ui
            BY-Product-Development/exec-wms-yard-management-ui-functional-tests
            BY-Product-Development/exec-wms-yard-management-map-service
            BY-Product-Development/exec-wms-daas-etl-blob-monitor-client
          DRY_RUN: false
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          CONCURRENCY: 2
          repositories_list_regex: false
        env:
          ARTIFACTORY_NPM_AUTH: ${{ secrets.EXEC_WMS_ARTIFACTORY_WM_CI_NPM_AUTH_TOKEN }}
          ARTIFACTORY_NPM_URL: ${{ secrets.DS_ARTIFACTORY_NPM_URL }}
      # For as long as Google doesn't support Dependabot Secrets
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: xt0rted Secrets Sync - Artifactory NPM
        uses: xt0rted/secrets-sync@v1
        with:
          repo_token: ${{ steps.get_workflow_token.outputs.token }}
          config: .github/secret-sync-artifactory-npm.yaml
        env:
          ARTIFACTORY_NPM_AUTH: ${{ secrets.EXEC_WMS_ARTIFACTORY_WM_CI_NPM_AUTH_TOKEN }}
          ARTIFACTORY_NPM_URL: ${{ secrets.DS_ARTIFACTORY_NPM_URL }}
      - name: Publish Failure Card
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: failure()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WMSPD_SYSTEMS_TEAM_GITHUBACTIONSNOTIFIY_WEBHOOK_URL }}
          show-on-start: false
          show-on-failure: true
          card-layout-exit: complete
          custom-facts: |
            - name: Failure Action
              value: "There is a failure with the new changes please resolve"